version: '3'
services:
  ui:
    container_name: work-timer-react
    image: ghcr.io/burnett2k/work-timer-react
    ports:
      - 5000:5000
    command: serve -s ./build
    environment:
      - REACT_APP_SERVER_BASE_URL=https://worktimer.xyz/api
  server:
    container_name: work-timer-api
    image: ghcr.io/burnett2k/work-timer-api
    ports:
      - 5002:5002
    command: yarn start
    environment:
      - CR_PAT
      - CLIENT_SECRET
      - CLIENT_ID
      - CLIENT_HOME_PAGE_URL
      - BASE_URL
      - SESSION_SECRET
      - MONGO_URI
