openapi: 3.0.1
info:
    title: Work Timer Api
    description: 'Testing out how to use this thing'
    version: 1.0.0
externalDocs:
    description: Find out more about Work Timer
    url: https://github.com/burnett2k/work-timer-react
servers:
    - url: http://localhost:8080
tags:
    - name: session
      description: A completed pomodoro sesssion
paths:
    /session:
        get:
            tags:
                - session
            summary: Retrieve a list of all sessions for the current user
            responses:
                200:
                    description: Ok
                    content: {}
                401:
                    description: Not Authenticated
                    content: {}
    /session/save:
        post:
            tags:
                - session
            summary: Saves a completed session
            responses:
                200:
                    description: Ok
                    content: {}
                401:
                    description: Not Authenticated
                    content: {}
    /session/summary:
        get:
            tags:
                - session
            summary: Retrieves a weekly summary of all sessions completed throughout time
            responses:
                200:
                    description: Ok
                    content: {}
                401:
                    description: Not Authenticated
                    content: {}
