name: build docker image and push to registry
on:
  pull_request:
    branches:
      - master
    paths:
      - '**.css'
      - '**.js'
      - '**.json'
      - '**.ts'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          provenance: false
          tags: ghcr.io/burnett2k/work-timer-react:latest
      - name: Build and push api
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/Dockerfile
          provenance: false
          push: true
          tags: ghcr.io/burnett2k/work-timer-api:latest
