name: deploy UI to remote server
on:
  push:
    branches:
      - master
    paths:
      - '**.js'
      - '**.css'
      - '**.json'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: copy file via ssh
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: 'docker-compose.yml'
          target: 'work-timer-react'
          rm: true
      - name: run bash script
        uses: appleboy/ssh-action@v0.1.4
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET}}
          CLIENT_ID: ${{ secrets.CLIENT_ID}}
          CLIENT_HOME_PAGE_URL: ${{ secrets.CLIENT_HOME_PAGE_URL}}
          BASE_URL: ${{ secrets.BASE_URL}}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET}}
          MONGO_URI: ${{ secrets.MONGO_URI}}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          envs: CR_PAT,CLIENT_SECRET,CLIENT_ID,CLIENT_HOME_PAGE_URL,BASE_URL,SESSION_SECRET,MONGO_URI
          script_stop: true
          script: |
            ##### WORK TIMER UI START #####

            /bin/bash 

            cd work-timer-react/

            # get id of currently running work timer docker container
            container=$(docker ps -a -q --filter ancestor=work-timer-react)

            # stop the docker container
            docker stop "$container" -t 1


            # delete old container to save space
            docker rm "$container"

            docker login https://ghcr.io/burnett2k/work-timer-react -u burnett2k -p $CR_PAT
            docker pull ghcr.io/burnett2k/work-timer-react:latest

            ###### WORK TIMER UI END #####
            # WORK TIMER API START
            # get id of currently running work timer docker container
            container=$(docker ps -a -q --filter ancestor=work-timer-api)

            # stop the docker container
            docker stop "$container"

            # delete old container to save space
            docker rm "$container"

            docker login https://ghcr.io/burnett2k/work-timer-api -u burnett2k -p $CR_PAT
            docker pull ghcr.io/burnett2k/work-timer-api:latest

            export CR_PAT=$CR_PAT
            export CLIENT_SECRET=$CLIENT_SECRET
            export CLIENT_ID=$CLIENT_ID
            export CLIENT_HOME_PAGE_URL=$CLIENT_HOME_PAGE_URL
            export BASE_URL=$BASE_URL
            export SESSION_SECRET=$SESSION_SECRET
            export MONGO_URI=$MONGO_URI

            # WORK TIMER API END

            docker-compose up -d

            docker ps
            echo "looks like it worked!!!"
