name: deploy UI to remote server
on:
  push:
    branches:
      - master
    paths:
      - '**.css'
      - '**.js'
      - '**.json'
      - '**.ts'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: copy file via ssh
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          passphrase: ${{ secrets.PASSWORD }}
          key: ${{ secrets.SSH_KEY }}
          source: 'docker-compose.yml'
          target: 'work-timer-react'
          rm: true
      - name: run bash script
        uses: appleboy/ssh-action@v0.1.4
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET}}
          CLIENT_ID: ${{ secrets.CLIENT_ID}}
          CLIENT_HOME_PAGE_URL: ${{ secrets.CLIENT_HOME_PAGE_URL}}
          BASE_URL: ${{ secrets.BASE_URL}}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET}}
          MONGO_URI: ${{ secrets.MONGO_URI}}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          passphrase: ${{ secrets.PASSWORD }}
          key: ${{ secrets.SSH_KEY }}
          envs: CR_PAT,CLIENT_SECRET,CLIENT_ID,CLIENT_HOME_PAGE_URL,BASE_URL,SESSION_SECRET,MONGO_URI
          script_stop: true
          script: |
            # AUTH TO DOCKER CONTAINER REGISTRY AND PULL #
            cd work-timer-react/

            docker login https://ghcr.io/burnett2k -u burnett2k -p $CR_PAT
            docker pull ghcr.io/burnett2k/work-timer-react:latest
            docker pull ghcr.io/burnett2k/work-timer-api:latest

            # ENV VARIABLE MGMT #
            export CR_PAT=$CR_PAT
            export CLIENT_SECRET=$CLIENT_SECRET
            export CLIENT_ID=$CLIENT_ID
            export CLIENT_HOME_PAGE_URL=$CLIENT_HOME_PAGE_URL
            export BASE_URL=$BASE_URL
            export SESSION_SECRET=$SESSION_SECRET
            export MONGO_URI=$MONGO_URI

            echo "composing our symphony of containers"
            docker-compose up -d

            echo "cleaning up dingleberries"
            docker system prune -a -f

            echo "currently running containers"
            docker ps
